from pathlib import Path

lines = [
    "# X Music & Entertainment Bot - OSS Edition",
    "",
    "A Python project for generating music and entertainment posts, then scheduling them through Buffer.",
    "",
    "## What it does",
    "",
    "- Generates human-style tweets for music, celebrity, festival, and pop culture topics.",
    "- Builds a daily posting schedule between 8am and 5pm.",
    "- Sends scheduled posts to Buffer via its GraphQL API.",
    "- Uses Groq for creative text generation, with a local fallback when Groq is unavailable.",
    "- Includes an RSS listener for music news content.",
    "",
    "## Requirements",
    "",
    "- Python 3.11+",
    "- requests",
    "- feedparser",
    "",
    "Install dependencies:",
    "",
    "  pip install -r requirements.txt",
    "",
    "## Configuration",
    "",
    "Edit config.py before running the bot:",
    "",
    "- BUFFER_API_KEY and BUFFER_CHANNEL_ID for Buffer publishing.",
    "- GROQ_API_KEY for Groq text generation.",
    "- GROQ_MODEL to choose the desired LLM.",
    "- POSTS_PER_DAY, POST_START_HOUR, POST_END_HOUR, and TIMEZONE.",
    "- TOPICS, TONES, and RSS feed URLs.",
    "",
    "## Usage",
    "",
    "### Generate and schedule daily posts",
    "",
    "Run this once each morning before your posting window:",
    "",
    "  python daily_prep.py",
    "",
    "This generates tweets, creates an 8am-5pm schedule, schedules them in Buffer, and saves a local backup at output/scheduled_posts.csv.",
    "",
    "### Check Buffer queue",
    "",
    "To review scheduled posts in Buffer:",
    "",
    "  python run_poster.py",
    "",
    "### Poll RSS feeds",
    "",
    "To fetch music news once and save new entries to the local database:",
    "",
    "  python rss_listener.py --once",
    "",
    "## Project structure",
    "",
    "- config.py - project settings, API keys, posting configuration, topics, and feeds.",
    "- generator.py - creates tweets using Groq and fallback templates.",
    "- scheduler.py - builds posting times and exports schedule CSV files.",
    "- buffer_poster.py - schedules posts in Buffer using GraphQL.",
    "- daily_prep.py - main daily workflow that generates and schedules posts.",
    "- run_poster.py - checks the Buffer scheduled queue and provides a manual poster utility.",
    "- rss_listener.py - polls RSS feeds and records new items to output/rss_posts.db.",
    "- requirements.txt - required Python libraries.",
    "",
    "## Notes",
    "",
    "- Buffer is the only proprietary service in this project.",
    "- Keep POSTS_PER_DAY below 100 for Buffer free plan compatibility.",
    "- The bot will still run with local fallback generation if Groq fails.",
]

Path("README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
